name: catatin
description: "Aplikasi pencatatan keuangan offline untuk UMKM — Catatin"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Database lokal
  sqflite: ^2.4.2
  path: ^1.9.1

  # Keamanan PIN
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6

  # Grafik
  fl_chart: ^0.70.2

  # File & Path
  path_provider: ^2.1.5
  file_picker: ^8.3.7
  share_plus: ^10.1.4

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpeg"
  min_sdk_android: 21
